"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 添加本地 simpleui 模块到 Python 路径
sys.path.insert(0, os.path.join(BASE_DIR, 'simpleui'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!$+cqtj%##m1-ofb&hy9ue2!fry2ao+^b)k9+f_o)uv@_x%!)e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # 添加 CORS 支持
    'dormitory_repair',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS 中间件，必须放在最前面
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import pymysql
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myproject',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Simple UI 配置
SIMPLEUI_DEFAULT_THEME = 'simpleui.css'
SIMPLEUI_HOME_TITLE = '宿舍报修管理系统'
SIMPLEUI_HOME_ICON = 'fa fa-home'
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = True

# 自定义logo
SIMPLEUI_LOGO = 'https://avatars2.githubusercontent.com/u/13655483?s=60&v=4'

# 是否收起菜单
SIMPLEUI_DEFAULT_ICON = True

# 登录成功后的默认跳转地址
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# 设置管理后台为默认首页
SIMPLEUI_INDEX = '/admin/'

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 自定义菜单
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['宿舍管理', '报修管理', '用户管理'],
    'dynamic': True,
    'menus': [
        {
            'name': '宿舍管理',
            'icon': 'fas fa-building',
            'models': [
                {
                    'name': '宿舍管理',
                    'icon': 'fa fa-bed',
                    'url': '/admin/dormitory_repair/dormitory/'
                },
                {
                    'name': '学生管理', 
                    'icon': 'fa fa-user-graduate',
                    'url': '/admin/dormitory_repair/student/'
                }
            ]
        },
        {
            'name': '报修管理',
            'icon': 'fas fa-tools',
            'models': [
                {
                    'name': '报修工单',
                    'icon': 'fa fa-clipboard-list',
                    'url': '/admin/dormitory_repair/repairorder/'
                }
            ]
        },
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户',
                    'icon': 'fa fa-user',
                    'url': '/admin/auth/user/'
                },
                {
                    'name': '组',
                    'icon': 'fa fa-users',
                    'url': '/admin/auth/group/'
                }
            ]
        }
    ]
}


# CORS 配置
# 允许所有域名访问（仅开发环境）
CORS_ALLOW_ALL_ORIGINS = True

# 如果不允许所有域名，可以指定具体域名
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]

# 允许的HTTP方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 允许携带认证信息
CORS_ALLOW_CREDENTIALS = True

# 预检请求的最大时间
CORS_PREFLIGHT_MAX_AGE = 86400



